### ISSUE TITLE
nvim-cmp是nvim自带的lsp吗

### ISSUE THREAD

**Issue by ilkl** [JavaHello/nvim#1]

**Comment by JavaHello** [comment]
[nvim-cmp](https://github.com/hrsh7th/nvim-cmp) 是自动补全插件，不只支持 LSP 补全，还有文件，buffer 等其它的功能

**Comment by JavaHello** [comment]
[nvim-cmp](https://github.com/hrsh7th/nvim-cmp) 是自动补全插件，不只支持 LSP 补全，还有文件，buffer 等其它的功能
