### ISSUE TITLE
mason.nvim在macos下无法正常下载

### ISSUE THREAD

**Issue by aoeivux** [JavaHello/nvim#18]
我确保README.md中的依赖都安装好了，版本也对应，但还是无法通过Lazy正常下载mason.nvim
<img width="958" alt="image" src="https://github.com/JavaHello/nvim/assets/74446305/3135bf24-959c-4fc6-b3eb-4fbb48cfd1ec">

**Comment by aoeivux** [comment]
在windows一切正常，在我的Macbook air m1 下却无法下载

**Comment by aoeivux** [comment]
我做了一个测试，删除了所有配置，只留下lazy,通过lazy下载mason，依然是同样的错误。我通过直接在`~/.local/share/nvim/lazy/`目录下直接通过`git clone `的方式，还是这样的错误，但是clone 其他的就可以， 太奇怪了。
<img width="899" alt="image" src="https://github.com/JavaHello/nvim/assets/74446305/ef0aab4b-57a1-48e3-b6e3-154230a48c16">

**Comment by JavaHello** [comment]
没有遇到过这个问题，尝试在其他目录 `clone` 试试

**Comment by aoeivux** [comment]
单独这个目录报错，其他目录都可以

**Comment by JavaHello** [comment]
> 单独这个目录报错，其他目录都可以

`mv` 过去看看能不能使用

**Comment by aoeivux** [comment]
谢谢回答，我重新启动了一边电脑，就好了。
