### ISSUE TITLE
Help dap for java

### ISSUE THREAD

**Issue by BOFA1ex** [JavaHello/nvim#2]
[问题]
`No configuration found for `help`. You need to add configs to `dap.configurations.help`.`

`~/.config/nvim/lua/kide/dap/codelldb.lua`
根据要求我添加了

```java
dap.adaptors.java = {
    type = "executable",
    command = os.getenv('HOME') .. '/usr/bin/java',
    args = { },
  }
  dap.configurations.java = {
    {
     type = "java",
     request = "launch",
     name = "Lanuch File",
     program = "${file}",
     javaPath = function()
        return '/usr/bin/java'
     end
    },
  }
```

但是没有解决问题，nvim初次使用没有经验，麻烦指导下.

**Comment by JavaHello** [comment]
Java 不需要手动添加 dap config, 打开项目`jdt.ls`启动完成后，执行 `:JdtRefreshDebugConfigs`命令会自动查询包含 `main`方法 `class` 添加到 `dap config`

**Comment by BOFA1ex** [comment]
感谢回复，对于给出的回答，我还有些疑问.
1. 打开项目如何确认jdt.ls是否启动完成，我目前是按:PackerStatus来确保nvim.jdtls是否loaded.
2. `JdtRefreshDebugConfigs` 没有找到相关的命令, 只有`JdtShowLogs`和`JdtWipeDataAndRestart`.

**Comment by JavaHello** [comment]
1. 目前貌似没有办法判断 `jdt.ls` 完全启动成功，可以尝试在 `on_attach` 里处理启动完成后的动作。
2. 确保这两个配置添加了
https://github.com/JavaHello/nvim/blob/3623489f61e2b367b97f6ee8c33847f41e193075/lua/kide/lsp/java.lua#L275-L276

**Comment by BOFA1ex** [comment]
1. `java.lua`配置如下

![image](https://user-images.githubusercontent.com/30573693/182317698-b67359e6-c8af-4b40-876d-e7c3dc5191f4.png)

3. `PackerStatus#nvim-jdtls` 算是加载了么?

![image](https://user-images.githubusercontent.com/30573693/182317996-faca2931-4a31-4c17-bf90-a702e91cfde9.png)

**Comment by JavaHello** [comment]
打开 `java` 文件会自动启动 `jdt.ls`。执行`:LspInfo` 看看`jdt.ls`是否已经启动

**Comment by BOFA1ex** [comment]
![image](https://user-images.githubusercontent.com/30573693/182326113-4f12637e-e14d-45a5-82c2-cf71d34de066.png)

`lsp.log`
![image](https://user-images.githubusercontent.com/30573693/182326917-156e8f5d-9aa5-4f76-942f-0aaad5ab64e3.png)

**Comment by JavaHello** [comment]
看起来是使用 `nvim-lsp-installer` 安装的，`lsp-config`启动的, 没有经过 `nvim-jdtls`。使用 `LspUninstall` 删除下 `jdtls`，参考 `REDEME.md` 文件里的[Java配置](https://github.com/JavaHello/nvim#java-%E9%85%8D%E7%BD%AE)试试

**Comment by BOFA1ex** [comment]
确实是用nvim-lsp-installer安装的jdtls.
README.md里的Java配置需要依赖vscode相关的java扩展包，没有其他的安装方式么?

**Comment by JavaHello** [comment]
可以手动下载编译，或者使用其它工具自动下载，然后修改配置[java.lua](https://github.com/JavaHello/nvim/blob/nvim-lsp/lua/kide/lsp/java.lua)文件里面的`jdtls_launcher`和其它扩展的文件路径。
> 推荐使用`vscode`下载扩展包，方便更新。

**Comment by BOFA1ex** [comment]
好的, 我试试. 感谢大佬耐心回复.
