### ISSUE TITLE
error：无法使用

### ISSUE THREAD

**Issue by CrankyKing** [JavaHello/nvim#28]
mac clone 下来以后 输入nvim报错：
E5113: Error while calling lua chunk: /Users/user/.config/nvim/lua/lazy_boot
strap.lua:2: attempt to index field 'uv' (a nil value)
stack traceback:
        /Users/user/.config/nvim/lua/lazy_bootstrap.lua:2: in main chunk
        [C]: in function 'require'
        /Users/user/.config/nvim/lua/kide/plugins/init.lua:1: in main chunk
        [C]: in function 'require'
        /Users/user/.config/nvim/init.lua:31: in main chunk

**Comment by JavaHello** [comment]
需要使用 `neovim-nightly` 版本的 neovim

**Comment by CrankyKing** [comment]
这个不是官网的neovim么 我直接brew install neovim下载的 ，但是把配置clone下来就还是报这个错，这个nightly该怎么下载呀 求大神教一下 感谢

**Comment by JavaHello** [comment]
https://github.com/neovim/neovim/wiki/Installing-Neovim
查看这里的安装步骤

**Comment by a823002162** [comment]
> https://github.com/neovim/neovim/wiki/Installing-Neovim 查看这里的安装步骤

已经参照链接里面的方法安装了neovim nightly,但是启动的时候还是报错,错误的内容和题主的一模一样,不知道是哪里设置的有问题,求大佬帮忙,感谢

**Comment by JavaHello** [comment]
> > https://github.com/neovim/neovim/wiki/Installing-Neovim 查看这里的安装步骤
> 
> 已经参照链接里面的方法安装了neovim nightly,但是启动的时候还是报错,错误的内容和题主的一模一样,不知道是哪里设置的有问题,求大佬帮忙,感谢
> 
> 环境设置: WSL2的Ubuntu18.04

是否能提供报错日志。

**Comment by a823002162** [comment]
抱歉没有找到日志在哪里,有一张截图可以吗
![image](https://github.com/JavaHello/nvim/assets/39456045/ae52c810-3036-496b-b279-5c06b53a120b)

**Comment by JavaHello** [comment]
> 抱歉没有找到日志在哪里,有一张截图可以吗 ![image](https://user-images.githubusercontent.com/39456045/261832469-ae52c810-3036-496b-b279-5c06b53a120b.png)

看起来是这个插件 install 失败了，可以在 `.local/share/nvim/lazy/markdown-preview.nvim/` 里面手动执行一下命令
```sh
cd app
yarn install
```

**Comment by a823002162** [comment]
感谢,但是执行命令后提示如下的错误:
![image](https://github.com/JavaHello/nvim/assets/39456045/c8669d94-7547-4690-845d-86aa1f8979ff)

除此之外,还有个小问题需要请教下,进入我的项目后,jdtls一直在执行对应的导入等操作,尤其是这个background task长时间没动静,而且cpu占用率有段时间非常高,这种情况正常吗,我应该继续等待还是需要排查下是不是哪里有问题,谢谢
![image](https://github.com/JavaHello/nvim/assets/39456045/d32911e0-72ed-44ef-870d-9b80560b874a)

**Comment by JavaHello** [comment]
> 除此之外,还有个小问题需要请教下,进入我的项目后,jdtls一直在执行对应的导入等操作,尤其是这个background task长时间没动静,而且cpu占用率有段时间非常高,这种情况正常吗,我应该继续等待还是需要排查下是不是哪里有问题,谢谢

- 可能是 yarn 版本问题，试试 `npm install` 看看
- `jdtls` 的问题,试试在命令行先执行 `mvn compile` 编译一下再打开。

**Comment by a823002162** [comment]
> > 除此之外,还有个小问题需要请教下,进入我的项目后,jdtls一直在执行对应的导入等操作,尤其是这个background task长时间没动静,而且cpu占用率有段时间非常高,这种情况正常吗,我应该继续等待还是需要排查下是不是哪里有问题,谢谢
> 
> * 可能是 yarn 版本问题，试试 `npm install` 看看
> * `jdtls` 的问题,试试在命令行先执行 `mvn compile` 编译一下再打开。

好的,非常感谢,已经可以正常的运行起来了,刚开始接触neovim,还不是很习惯,很多键位需要对着keybinds慢慢熟悉,再次感谢大佬,让小白的我可以轻松的用上Neovim
