### ISSUE TITLE
luasnip 在windows m下

### ISSUE THREAD

**Issue by jiadsii** [JavaHello/nvim#47]
luasnip 在windows 下编译出错。

  Failed (1)
    ● LuaSnip 71.48ms  cmp_luasnip
        git submodule init
        git submodule update
        make "CC=cc" "INCLUDE_DIR=-I'/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/lua51_include/'" LDLIBS="" -C "deps/jsregexp"
        make[1]: Entering directory 'C:/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/jsregexp'
        cc -I'/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/lua51_include/' -O2 -fPIC -c jsregexp.c -o jsregexp.o
        process_begin: CreateProcess(NULL, cc -I/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/lua51_include/ -O2 -fPIC -c jsregexp.c -o jsregexp.o, ...) failed.
        make (e=2): El sistema no puede encontrar el archivo especificado.
        make[1]: *** [Makefile:20: jsregexp.o] Error 2
        make[1]: Leaving directory 'C:/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/jsregexp'
        make: *** [Makefile:49: jsregexp] Error 2

后尝试手动编译jsregexp

**Comment by jiadsii** [comment]
尝试下LuaSnip\deps\jsregexp>make    
出错
gcc -shared -Wl,-undefined,dynamic_lookup jsregexp.o cutils.o libregexp.o libunicode.o  -o 
jsregexp.so
jsregexp.o:jsregexp.c:(.text+0x19): undefined reference to `luaL_checklstring'
jsregexp.o:jsregexp.c:(.text+0x42): undefined reference to `luaL_argerror'
jsregexp.o:jsregexp.c:(.text+0x71): undefined reference to `lua_type'
jsregexp.o:jsregexp.c:(.text+0xc7): undefined reference to `lua_newuserdata'



是不是没有指定lua51.dll, 如何指定

jsregexp 下的 makefile
修改如下

# This file is meant for testing locally, it is not used by luarocks.

TARGET = jsregexp.so
SOURCES = jsregexp.c cutils.c libregexp.c libunicode.c
OBJECTS = $(SOURCES:%.c=%.o)
INCLUDE_DIR = -I'C:/Users/codeHavenotEmotion/scoop/apps/lua51/current'
LDLIBS = 'C:/Users/codeHavenotEmotion/scoop/apps/lua51/current'
LDFLAGS = -shared -Wl,-undefined,dynamic_lookup
CFLAGS = $(INCLUDE_DIR) -O2 -fPIC
CC = gcc

问题还是没有解决

**Comment by JavaHello** [comment]
参考这里https://github.com/L3MON4D3/LuaSnip/issues/986

**Comment by jiadsii** [comment]
ok,do it.

在msys2,中 执行 
```
pacman -Syu,

pacman -S mingw-w64-ucrt-x86_64-luajit,  mingw-w64-ucrt-x86_64-make,  mingw-w64-ucrt-x86_64-gcc
```
修改 makefile 文件
```

$(TARGET): $(OBJECTS)
	$(CC) $^ $(LDLIBS) -o $@ $(LDFLAGS)



INCLUDE_DIR = -I/ucrt64/include/luajit-2.1
LDLIBS = -llua5.1 
LDFLAGS = -shared -lluajit-5.1
CFLAGS = $(INCLUDE_DIR) -O2 -fPIC
CC = gcc
```

在ucrt64 shell 中执行 
```
 mingw32-make CC=gcc CFLAGS="-I/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC" LDFLAGS="-shared -lluajit-5.1" install_jsregexp
```


now , you can see

```
git submodule init
git submodule update
E:/code/msys64/ucrt64/bin/mingw32-make.exe "CC=gcc" "INCLUDE_DIR=-I'/c/Users/codeHavenotEmotion/AppD
ata/Local/nvim-data/lazy/LuaSnip/deps/lua51_include/'" LDLIBS="" -C "deps/jsregexp"
mingw32-make[1]: Entering directory 'C:/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSni
p/deps/jsregexp'
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c jsregexp.c -o jsregexp.o
In function 'jsstring_new',
    inlined from 'jsstring_new' at jsregexp.c:123:12:
jsregexp.c:145:13: warning: 'input_utf16_len' may be used uninitialized [-Wmaybe-uninitialized]
  145 |     ud->len = input_utf16_len;
      |     ~~~~~~~~^~~~~~~~~~~~~~~~~
jsregexp.c: In function 'jsstring_new':
jsregexp.c:136:14: note: 'input_utf16_len' was declared here
  136 |     uint32_t input_utf16_len;
      |              ^~~~~~~~~~~~~~~
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c cutils.c -o cutils.o
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c libregexp.c -o libregexp.o
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c libunicode.c -o libunicode.o
gcc jsregexp.o cutils.o libregexp.o libunicode.o  -o jsregexp.so -shared -lluajit-5.1
mingw32-make[1]: Leaving directory 'C:/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip
/deps/jsregexp'
E:/code/msys64/ucrt64/bin/mingw32-make.exe "CC=gcc" "INCLUDE_DIR=-I'/c/Users/codeHavenotEmotion/AppD
ata/Local/nvim-data/lazy/LuaSnip/deps/lua51_include/'" LDLIBS="" -C "deps/jsregexp005"
mingw32-make[1]: Entering directory 'C:/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSni
p/deps/jsregexp005'
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c jsregexp.c -o jsregexp.o
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c cutils.c -o cutils.o
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c libregexp.c -o libregexp.o
gcc -IE:/code/msys64/ucrt64/include/luajit-2.1 -O2 -Wall -fPIC -c libunicode.c -o libunicode.o
gcc jsregexp.o cutils.o libregexp.o libunicode.o  -o jsregexp.so -shared -lluajit-5.1
mingw32-make[1]: Leaving directory 'C:/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip
/deps/jsregexp005'
# remove old binary.
rm "/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/lua/luasnip-jsregexp.so" || tru
e
rm: cannot remove '/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/lua/luasnip-jsre
gexp.so': No such file or directory
# there is some additional trickery to make this work with jsregexp-0.0.6 in
# util/jsregexp.lua.
cp "/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/jsregexp/jsregexp.lua" "/c
/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/lua/luasnip-jsregexp.lua"
# just move out of jsregexp-directory, so it is not accidentially deleted.
cp "/c/Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/jsregexp/jsregexp.so" "/c/
Users/codeHavenotEmotion/AppData/Local/nvim-data/lazy/LuaSnip/deps/luasnip-jsregexp.so"


```

do it.
