### ISSUE TITLE
java jar 文件预览

### ISSUE THREAD

**Issue by my0811** [JavaHello/nvim#49]
telescope 配合 jdtls 预览jar 中的class文件,感觉非常卡顿

**Comment by JavaHello** [comment]
取决于 lsp 服务器响应速度。使用 `fzf-lua` 预览 jar 中的 class，体验会好一点. 或者试试 `nvchad` 分支，精简了许多配置，

**Comment by my0811** [comment]
我试试,多谢,你主要是从事java 开发吗? 并且是一个vim爱好者

**Comment by my0811** [comment]
jdtls 返回的路径特别长,而且可读性太差,我利用 telescope 做了 path format 做了一些优化,目前展示的和idea 效果差不多, 不知道你有没有这方面的优化, fzf-lua  symbol 如何能做到这样呢,看文档好像没有自己格式化的配置暴漏


![image](https://github.com/JavaHello/nvim/assets/20672932/4c3403b4-46f7-49e9-b9f4-c1c29b820320)

**Comment by JavaHello** [comment]
> 我试试,多谢,你主要是从事java 开发吗? 并且是一个vim爱好者

是的，vim 使用习惯了

**Comment by JavaHello** [comment]
> jdtls 返回的路径特别长,而且可读性太差,我利用 telescope 做了 path format 做了一些优化,目前展示的和idea 效果差不多, 不知道你有没有这方面的优化, fzf-lua symbol 如何能做到这样呢,看文档好像没有自己格式化的配置暴漏
> 
> ![image](https://private-user-images.githubusercontent.com/20672932/333000303-4c3403b4-46f7-49e9-b9f4-c1c29b820320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDMxNTYsIm5iZiI6MTcxNjQ0Mjg1NiwicGF0aCI6Ii8yMDY3MjkzMi8zMzMwMDAzMDMtNGMzNDAzYjQtNDZmNy00OWU5LWI5ZjQtYzFjMjliODIwMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA1NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjc4NDY5Y2U2NmRjNTEzYWQzZTllZTU2OTIxMGY2ZmRjNTEzZjk0YmMxZmRiNjg3YjgwYTU0Y2ZmOGU2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bDxkVKZuIqBQrhnU-Z4Hc3WLjk34cU1mNn4SjHbTmOg)

牛的，看文档好像没有提供相关的配置，可以在 fzf-lua 那边问下。不过也可以使用原生的 quickfix， 格式化 quickfix 的输出

**Comment by JavaHello** [comment]
https://github.com/JavaHello/nvim/commit/f6fdf223ade7a1990f92628045c6d487ac4a3cc6
