### ISSUE TITLE
在我首次打开java文件时候

### ISSUE THREAD

**Issue by Zatermelon** [JavaHello/nvim#50]
  Error  11:39:33 msg_show.lua_error Error detected while processing FileType Autocommands for "java":
11:39:33 msg_show Error executing lua callback: ...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:225: cmd: expected list, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua:764: in function 'validate'
	...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:225: in function '_cmd_parts'
	...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:300: in function 'validate_client_config'
	...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:1013: in function 'start_client'
	...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:885: in function 'start'
	...im-data/lazy/spring-boot.nvim/lua/spring_boot/launch.lua:151: in function <...im-data/lazy/spring-boot.nvim/lua/spring_boot/launch.lua:144>
	[C]: in function 'nvim_exec_autocmds'
	...Data/Local/nvim-data/lazy/NvChad/lua/nvchad/autocmds.lua:62: in function <...Data/Local/nvim-data/lazy/NvChad/lua/nvchad/autocmds.lua:61>

![023701a497325cf986326952bf3d1e9](https://github.com/JavaHello/nvim/assets/49584890/ad6342cd-73bb-42a6-8a5e-8b5f0ebf5b8f)

**Comment by Zatermelon** [comment]
i need help!i'm neovim noob🥺

**Comment by JavaHello** [comment]
你需要安装 vscode-spring-boot， 或者指定 ls_path , 参考 [spring-boot.nvim](https://github.com/JavaHello/spring-boot.nvim)
