### ISSUE TITLE
jdtl配置是否需要依赖vscode生成的相关内容

### ISSUE THREAD

**Issue by LicsDaSheng** [JavaHello/nvim#7]
要想jdtl完美工作，是不是需要先用vscode打开工程，生成对应的 .vscode文件才行

**Comment by oncekey** [comment]
或者能罗列一下 依赖的vscode的java 插件有哪些么？

**Comment by JavaHello** [comment]
> 要想jdtl完美工作，是不是需要先用vscode打开工程，生成对应的 .vscode文件才行

不需要

**Comment by JavaHello** [comment]
> 或者能罗列一下 依赖的vscode的java 插件有哪些么？

README Java 部分，这里写了安装步骤
https://javahello.github.io/dev/tools/NVIM-LSP-Java-IDE-vscode.html
